### ISSUE TITLE
Refresh appear in front of searchbar

### ISSUE THREAD

**Issue by AzSiAz** [gh123man/Refresher#2]
Not sure if something can be done about this but just in case
![image](https://user-images.githubusercontent.com/7109680/171221685-0c7ccde2-f5e0-4f44-9572-c37bc244dd0b.png)

**Comment by gh123man** [comment]
I have not tried the search bar yet. I'll try to reproduce it and see if I can work around it.

**Comment by gh123man** [comment]
Ok I think I reproduced the behavior - let me know if this is what you are seeing: 

## spinner overlayed by search bar during animation
![search-weird](https://user-images.githubusercontent.com/959778/171293237-227f2110-d401-418c-a302-347fbf1324a9.gif)

It looks like it only overlays the search bar while you are scrolling - which is currently unavoidable. 


it appears this is not a problem on a sub-page in the navigation stack:

## Good behavior on subview
![search-better](https://user-images.githubusercontent.com/959778/171293236-f86b7202-f8df-4412-a1e4-730bb1a5c0d1.gif)


I recommend using the default style in these cases since it works nicer with "fixed" headers (like the search bar)

## How it looks with `style: .default`
![search-default](https://user-images.githubusercontent.com/959778/171293235-30f6bcb5-3d24-4aa8-8969-b6cbcefb0020.gif)

## Other bugs
- ~~I did find a couple of other small bugs with the header insets not being big enough to accommodate the search view (with `style: .default` - stay tuned, will post an update soon.~~ - fixed

**Comment by AzSiAz** [comment]
It's also going over (under ?) LargeTitle (in subview) from what I am seeing on my app with `.system` style  but as you say for searchbar this is also unavoidable I think

I think it's not a problem with the searchbar but with navbar and large title
I am going to switch to inline title and use `.default` when not possible

**Comment by gh123man** [comment]
@AzSiAz  How do you feel about this as a fix? 
I know it's not *exactly* like the system refresher. but it solves the problem of needing to be in a fixed part of the screen and looks pretty similar. 

I am thinking of adding this as `style: .system2`. 
![fix](https://user-images.githubusercontent.com/959778/171311079-c11d89b2-0dbe-4df1-8df7-4dfad8ba7a37.gif)

**Comment by gh123man** [comment]
I pushed this change in `1.0.9`. use `style: .system2`. Ill add it to the readme/examples once it's stable (I haven't tested it thoroughly)

**Comment by AzSiAz** [comment]
Might work for some people, not sure how I feel about it I think refresh icon appear to late for my taste 🤔
Still it might be useful for some people so it's a nice addition 👍

Not sure it's possible but since animation & large title min and max are constant is it possible to detect/pass a bool to refresher for large title and apply some kind of offset on scroll down (for `.system`) ?

**Comment by gh123man** [comment]
> Not sure it's possible but since animation & large title min and max are constant is it possible to detect/pass a bool to refresher for large title and apply some kind of offset on scroll down

(if I am understanding this correctly) that's what `style: .system2` is doing. As you pull down a spacer is opened up at the top of the scrollview to push down the content and the refresh spinner is centered in that view. 

Conversely with `style: .system` - the spacer is only added after the scroll is released and the spinner is offset inverse to the scroll amount (so it stays in a fixed location on the screen). 
So a nice middle ground may be to use `.system2` for large title views, and `.system` for subviews that have a fixed navbar.

**Comment by AzSiAz** [comment]
> (if I am understanding this correctly) that's what style: .system2 is doing. As you pull down a spacer is opened up at the top of the scrollview to push down the content and the refresh spinner is centered in that view.

Ah, my bad. I should have read the commit code 😅 

I just tried `system2` and it seem largely good enough for a third party refresher limited by what is currently possible with SwiftUI navbar, let's hope they add `refreshable` support to ScrollView at WWDC22

Closing since `system2` is the answer to my problem, thanks 😄
