### ISSUE TITLE
Try use it in List but can‘t show List

### ISSUE THREAD

**Issue by Rex-xingjl** [gh123man/Refresher#4]
Would you try make it usefully when use List？ List has some special features that I need

**Comment by eyuxin** [comment]
Is there any progress? I also want a version that supports List for ios 14

**Comment by Rex-xingjl** [comment]
> Is there any progress? I also want a version that supports List for ios 14

List is hard to programming, I had to fix it myself by using ScrollView & LazyVStack. I will release my solution a few days later.
https://github.com/Rex-xingjl/SwiftUI-Refreshable-List

**Comment by gh123man** [comment]
👋 Hi - I haven't tested this on a list view. +1 to @Rex-xingjl list views are hard because they do some magic. 
`ScrollView` + `LazyVStack` accomplishes effectively the same thing with more flexibility so that's a great workaround for now. 

Ill try to dedicate some time to test this with a list view and see what (if anything) can be done.

**Comment by gh123man** [comment]
Due to the way lists are designed in SwiftUI, this is fundamentally difficult (perhaps impossible) to support. So I am going to close this.
