### ISSUE TITLE
Great idea!

### ISSUE THREAD

**Issue by wdq123550** [gh123man/Refresher#7]
And support pull up load more?

**Comment by gh123man** [comment]
Thanks for the feedback.
This is an interesting idea. I'll think about it and consider adding it in a future version

**Comment by gh123man** [comment]
Not exactly "pull up" to load more, but I have written another library (that works well with this library) to support loading more content as you scroll down. You can check it out here. 

https://github.com/gh123man/ScrollViewLoader

Otherwise - I do not plan to add a "pull up" to load more to this library at this time.
